another round of compatibility checking for mac os x
Former-commit-id: 79c5e6fcece517d2d0bcd5797dd01aacf99bc22d
Former-commit-id: fc2fa6ffeeb48cc39c37de24ec8c70f4015eeb24

diff --git a/runme b/runme
--- a/runme
+++ b/runme
@@ -487,6 +487,128 @@ cd ..
 
 fi  # end of omnetpp installation
 
+################################
+## Start of SUMO installation ##
+################################
+# following instructions in here
+# http://sumo.dlr.de/wiki/Installing/MacOS_Build_w_Homebrew
+
+# change directory to VENTOS
+cd $DIR
+# change directory to parent of VENTOS
+cd ..
+
+echo ""
+echo "Check main libraries for SUMO"
+echo "============================="
+
+if [[ "$OS" == "Ubuntu" ]]; then
+    # should we add "libxerces-c2-dev" ? installing libgdal-dev removes libxerces-c2-dev!
+    libs=("automake" "autoconf" "pkg-config" "libfox-1.6-dev" "libproj-dev" "libgdal-dev")
+    install_LIB_linux libs[@]
+elif [[ "$OS" == "Mac OS X" ]]; then
+    libs=("automake" "autoconf" "pkg-config" "homebrew/x11/fox" "proj" "gdal" "xerces-c")
+    install_LIB_Mac libs[@]
+fi
+
+echo ""
+echo "Preparing to install SUMO"
+echo "========================="
+
+ver=$(sumo 2> /dev/null | grep 'SUMO Version' | awk '{print $3}')
+if [[ "" != "$ver" ]]; then
+    loc=$(which sumo)
+    echo "found SUMO $ver in"
+    echo "    $loc"
+    echo "skip downloading/making SUMO"    
+else
+
+echo ""
+echo "Cloning SUMO git repository"
+echo "==========================="
+# check if SUMO directory exists
+if [ ! -d "VENTOS_SUMO" ]; then
+    # cloning git
+    if ! git clone https://github.com/ManiAm/VENTOS_SUMO; then
+        exit 1
+    fi
+    # make sure the folder is created
+    if [[ ! -d "VENTOS_SUMO" ]]; then
+        echo "VENTOS_SUMO folder does not exist!"
+        exit 1
+    fi
+else
+    echo "VENTOS_SUMO folder already exists!"
+fi
+
+echo ""
+echo "Running SUMO configure"
+echo "======================"
+
+cd VENTOS_SUMO
+
+if [[ "$OS" == "Mac OS X" ]]; then
+    # homebrew installs xquartz in /opt/x11/
+    export CPPFLAGS="$CPPFLAGS -I/opt/X11/include/"
+    export LDFLAGS="-L/opt/X11/lib"
+fi
+
+echo "generating configure file ..."
+make -f Makefile.cvs > /dev/null
+
+echo "running configure ..."
+confOut=$( { ./configure --enable-debug --with-proj-gdal=/usr/local > /tmp/VENTOS_tmp/out.xzevap; } 2>&1 )
+printf "%s \n" "$confOut"
+
+# should we terminate this script
+check=$(echo "$confOut" | grep -e "error" -e "configure: WARNING")
+if [ "" != "$check" ]; then
+    echo ""    # insert new line for readability
+    exit 1
+fi
+
+# check if SUMO bin is in the path
+SUMO_BIN_DIR=$(pwd)"/bin"
+if [[ ! -d $SUMO_BIN_DIR ]]; then
+   echo "The $SUMO_BIN_DIR directory does not exist!"
+   exit 1
+else
+  # ...then we create a small tmp file to check if the dir is in the path
+  probefile=__second__probe__
+
+  echo '' >$SUMO_BIN_DIR/$probefile
+  chmod +x  $SUMO_BIN_DIR/$probefile
+
+  if ($probefile) >/dev/null 2>/dev/null; then
+    echo "Your PATH contains $SUMO_BIN_DIR. Good!"
+  else
+      printf "WARNING: your PATH doesn't contain $SUMO_BIN_DIR! \nAdd the following line to your .profile or .bash_profile (provided you use bash): \nexport PATH=\$PATH:$SUMO_BIN_DIR \n"
+      printf "\n\e[1;31mAfter changing PATH, close this terminal and run the script again!\e[0m \n"
+      # removing the prob file
+      rm $SUMO_BIN_DIR/$probefile
+      exit 1
+  fi
+
+  # removing the prob file
+  rm $SUMO_BIN_DIR/$probefile
+fi
+
+echo ""
+echo "Making SUMO"
+echo "==========="
+
+# start making SUMO
+printf "\e[1;32mcompiling takes some time, so relax and \nwatch: https://www.youtube.com/watch?v=BlFdAm2AjAk \e[0m \n"
+echo " "
+make -j4 > /dev/null
+echo "make is finished!"
+
+# go out of SUMO folder
+cd ..
+
+fi # end of SUMO installation
+
+
 ###############################
 ## Start VENTOS installation ##
 ###############################
@@ -664,7 +786,8 @@ elif [[ "$OS" == "Mac OS X" ]]; then
 fi
 
 result=$?
-if [[ ("$result" == "1") || ("$result" == "2") ]]; then
+#if [[ ("$result" == "1") || ("$result" == "2") ]]; then
+if [[ 1 ]]; then
     if [ ! -f "snmp++-3.3.5.tar.gz" ]; then
         # download snmp++ API
         echo "downloading snmp++"
@@ -722,165 +845,38 @@ echo "Installing shark"
 echo "================"
 
 # libshark library will be copied into /usr/local/lib and the header files will be copied into /usr/local/include.
+# in mac os x, brew install shark does not make symbolic links for include:
+# sudo ln -s /usr/local/Cellar/shark/3.0.0/include/shark /usr/local/include
+# moreover, we need shark_debug shared library. So shark should be compiled manually!
 
-if [[ "$OS" == "Ubuntu" ]]; then
-    getLibVersions_Linux "libshark" "3.0.0"
+getLibVersions_Linux "libshark" "3.0.0"
 
-    result=$?
-    if [[ ("$result" == "1") || ("$result" == "2") ]]; then
-        if [ ! -d "Shark" ]; then
-            echo "downloading shark"
-            curl -o shark.zip -LOk https://github.com/Shark-ML/Shark/archive/master.zip
-            unzip shark.zip -d Shark > /dev/null
-        fi
-
-        cd Shark
-        cd Shark-master
-
-        echo "installing shark ..."
-        mkdir build
-        cd build
-        cmake "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DBUILD_SHARED_LIBS=ON" "-DCMAKE_BUILD_TYPE=Debug" ../ > /dev/null
-        make 
-        sudo make install > /dev/null
-
-        cd ..
-        cd ..
-        cd ..
-    else
-        echo "libshark is already installed!"
+result=$?
+#if [[ ("$result" == "1") || ("$result" == "2") ]]; then
+if [[ 1 ]]; then
+    if [ ! -d "Shark" ]; then
+        echo "downloading shark"
+        curl -o shark.zip -LOk https://github.com/Shark-ML/Shark/archive/master.zip
+        unzip shark.zip -d Shark > /dev/null
     fi
 
-# in mac OS, shark installation is much easier thanks to brew
-elif [[ "$OS" == "Mac OS X" ]]; then
-    libs=("homebrew/science/shark")
-    install_LIB_Mac libs[@]
+    cd Shark
+    cd Shark-master
 
-    # we need to create a sym link manually?!
-    sudo ln -s /usr/local/Cellar/shark/3.0.0/include/shark /usr/local/include
-fi
+    echo "installing shark ..."
+    mkdir build
+    cd build
+    cmake "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DBUILD_SHARED_LIBS=ON" "-DCMAKE_BUILD_TYPE=Debug" ../ > /dev/null
+    make 
+    sudo make install > /dev/null
 
-
-################################
-## Start of SUMO installation ##
-################################
-# following instructions in here
-# http://sumo.dlr.de/wiki/Installing/MacOS_Build_w_Homebrew
-
-# change directory to VENTOS
-cd $DIR
-# change directory to parent of VENTOS
-cd ..
-
-echo ""
-echo "Check main libraries for SUMO"
-echo "============================="
-
-if [[ "$OS" == "Ubuntu" ]]; then
-    # should we add "libxerces-c2-dev" ? installing libgdal-dev removes libxerces-c2-dev!
-    libs=("automake" "autoconf" "pkg-config" "libfox-1.6-dev" "libproj-dev" "libgdal-dev")
-    install_LIB_linux libs[@]
-elif [[ "$OS" == "Mac OS X" ]]; then
-    libs=("automake" "autoconf" "pkg-config" "homebrew/x11/fox" "proj" "gdal" "xerces-c")
-    install_LIB_Mac libs[@]
-fi
-
-echo ""
-echo "Preparing to install SUMO"
-echo "========================="
-
-ver=$(sumo 2> /dev/null | grep 'SUMO Version' | awk '{print $3}')
-if [[ "" != "$ver" ]]; then
-    loc=$(which sumo)
-    echo "found SUMO $ver in"
-    echo "    $loc"
-    echo "skip downloading/making SUMO"    
+    cd ..
+    cd ..
+    cd ..
 else
-
-echo ""
-echo "Cloning SUMO git repository"
-echo "==========================="
-# check if SUMO directory exists
-if [ ! -d "VENTOS_SUMO" ]; then
-    # cloning git
-    if ! git clone https://github.com/ManiAm/VENTOS_SUMO; then
-        exit 1
-    fi
-    # make sure the folder is created
-    if [[ ! -d "VENTOS_SUMO" ]]; then
-        echo "VENTOS_SUMO folder does not exist!"
-        exit 1
-    fi
-else
-    echo "VENTOS_SUMO folder already exists!"
+    echo "libshark is already installed!"
 fi
 
-echo ""
-echo "Running SUMO configure"
-echo "======================"
-
-cd VENTOS_SUMO
-
-if [[ "$OS" == "Mac OS X" ]]; then
-    # homebrew installs xquartz in /opt/x11/
-    export CPPFLAGS="$CPPFLAGS -I/opt/X11/include/"
-    export LDFLAGS="-L/opt/X11/lib"
-fi
-
-echo "generating configure file ..."
-make -f Makefile.cvs > /dev/null
-
-echo "running configure ..."
-confOut=$( { ./configure --enable-debug --with-proj-gdal=/usr/local > /tmp/VENTOS_tmp/out.xzevap; } 2>&1 )
-printf "%s \n" "$confOut"
-
-# should we terminate this script
-check=$(echo "$confOut" | grep -e "error" -e "configure: WARNING")
-if [ "" != "$check" ]; then
-    echo ""    # insert new line for readability
-    exit 1
-fi
-
-# check if SUMO bin is in the path
-SUMO_BIN_DIR=$(pwd)"/bin"
-if [[ ! -d $SUMO_BIN_DIR ]]; then
-   echo "The $SUMO_BIN_DIR directory does not exist!"
-   exit 1
-else
-  # ...then we create a small tmp file to check if the dir is in the path
-  probefile=__second__probe__
-
-  echo '' >$SUMO_BIN_DIR/$probefile
-  chmod +x  $SUMO_BIN_DIR/$probefile
-
-  if ($probefile) >/dev/null 2>/dev/null; then
-    echo "Your PATH contains $SUMO_BIN_DIR. Good!"
-  else
-      printf "WARNING: your PATH doesn't contain $SUMO_BIN_DIR! \nAdd the following line to your .profile or .bash_profile (provided you use bash): \nexport PATH=\$PATH:$SUMO_BIN_DIR \n"
-      printf "\n\e[1;31mAfter changing PATH, close this terminal and run the script again!\e[0m \n"
-      # removing the prob file
-      rm $SUMO_BIN_DIR/$probefile
-      exit 1
-  fi
-
-  # removing the prob file
-  rm $SUMO_BIN_DIR/$probefile
-fi
-
-echo ""
-echo "Making SUMO"
-echo "==========="
-
-# start making SUMO
-printf "\e[1;32mcompiling takes some time, so relax and \nwatch: https://www.youtube.com/watch?v=BlFdAm2AjAk \e[0m \n"
-echo " "
-make -j4 > /dev/null
-echo "make is finished!"
-
-# go out of SUMO folder
-cd ..
-
-fi # end of SUMO installation
 
 ######################
 ## Finishing up ... ##
