we now clone VENTOS_SUMO
Former-commit-id: 4844d674fab1d774aaa38a63005c59df735206b5
Former-commit-id: 6af6c5ed6a2eb12adbf003cbd23e30ba7efea096

diff --git a/runme b/runme
--- a/runme
+++ b/runme
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-#if [ "$EUID" -ne 0 ]; then 
-#  echo "Please run as root"
-#  exit 1
-#fi
+if [ "$EUID" -eq 0 ]; then 
+  printf "\e[1;31mNo! No! No! Do not run the script with sudo permission! \e[0m \n\n"
+  exit 1
+fi
 
 echo "Bash version is: $BASH_VERSION$"
 
@@ -32,13 +32,17 @@ echo "Detected OS:" $OSTYPE $OS $VER "("$CODENAME")", $ARCH
 arrIN=(${VER//./ })
 VER_major=${arrIN[0]}
 VER_minor=${arrIN[1]}
-if [[ ("$OSTYPE" == "linux-gnu" && "$OS" == "Ubuntu" && "$VER_major" == "14" && "$VER_minor" == "04" && "$ARCH" == "x86_64") ]]; then
+
+if [[ ("$OSTYPE" == "linux-gnu" && "$OS" == "Ubuntu" && "$VER_major" == "15" && "$VER_minor" == "10") ]]; then
     echo "Starting script ..."
 
-elif [[ ("$OSTYPE" == "linux-gnu" && "$OS" == "Ubuntu" && "$VER_major" == "12" && "$VER_minor" == "04" && "$ARCH" == "x86_64") ]]; then
+elif [[ ("$OSTYPE" == "linux-gnu" && "$OS" == "Ubuntu" && "$VER_major" == "14" && "$VER_minor" == "04") ]]; then
     echo "Starting script ..."
 
-elif [[ ("$OSTYPE" == "darwin"* && "$OS" == "Mac OS X" && "$VER_major" == "10" && "$VER_minor" == "11" && "$ARCH" == "x86_64") ]]; then
+elif [[ ("$OSTYPE" == "linux-gnu" && "$OS" == "Ubuntu" && "$VER_major" == "12" && "$VER_minor" == "04") ]]; then
+    echo "Starting script ..."
+
+elif [[ ("$OSTYPE" == "darwin"* && "$OS" == "Mac OS X" && "$VER_major" == "10" && "$VER_minor" == "11") ]]; then
     echo "Starting script ..."
 
     # check if Command Line Tools is installed
@@ -288,11 +292,25 @@ if [[ "$result" == "2" ]]; then
     fi
 fi
 
-if [[ "$OS" == "Ubuntu" ]]; then
-    # refresh the databse of available packages
-    echo "updating available packages ..."
-    sudo apt-get update > /dev/null
+# refresh the databse of available packages
+echo "updating available packages ..."
+sudo apt-get update > /dev/null
 
+echo ""
+echo "Checking downloaders"
+echo "===================="
+libs=("lftp" "curl")  # curl is prefered over wget since Mac OS X has curl by default
+if [[ "$OS" == "Ubuntu" ]]; then
+    install_LIB_linux libs[@]
+elif [[ "$OS" == "Mac OS X" ]]; then
+    install_LIB_Mac libs[@]
+fi
+
+################################
+## Start OMNET++ installation ##
+################################
+
+if [[ "$OS" == "Ubuntu" ]]; then
     echo ""
     echo "Check main libraries for OMNET++"
     echo "================================"
@@ -312,18 +330,11 @@ if [[ "$OS" == "Ubuntu" ]]; then
     libs=("qt4-qmake" "libqt4-dev" "libqt4-opengl-dev" "openscenegraph" "libopenscenegraph-dev" "openscenegraph-plugin-osgearth" "osgearth" "osgearth-data" "libosgearth-dev")
     install_LIB_linux libs[@]
 
-    echo ""
-    echo "Checking downloaders"
-    echo "===================="
-    libs=("lftp" "curl")  # curl is prefered over wget since Mac OS X has curl by default
-    install_LIB_linux libs[@]
-
 elif [[ "$OS" == "Mac OS X" ]]; then
-
     echo ""
     echo "Check main libraries for OMNET++"
     echo "================================"
-    libs=("open-mpi" "lftp" "curl" "Caskroom/cask/xquartz")
+    libs=("open-mpi" "Caskroom/cask/xquartz")
     install_LIB_Mac libs[@]
 fi
 
@@ -482,8 +493,11 @@ if [[ "$OS" == "Ubuntu" ]]; then
     else
         boostLIB="libboost-all-dev"
     fi
-
-    libs=("$boostLIB" "libssl-dev" "libcurl4-gnutls-dev" "libxerces-c2-dev" "libfox-1.6-dev" "libproj-dev" "gnuplot" "gnuplot-x11" "cmake" "cmake-curses-gui" "libusb-1.0-0-dev" "libtool" "automake" "autotools-dev" "libudev-dev" "libatlas-base-dev")
+    
+    # "cmake" "cmake-curses-gui" are used by eigen and shark
+    # "libtool" "automake" "autotools-dev" "libudev-dev" are for making libusb
+    # "libatlas-base-dev" is for shark
+    libs=("$boostLIB" "libssl-dev" "libcurl4-gnutls-dev" "gnuplot" "gnuplot-x11" "cmake" "cmake-curses-gui" "libusb-1.0-0-dev" "libtool" "automake" "autotools-dev" "libudev-dev" "libatlas-base-dev")
     install_LIB_linux libs[@]
 
 elif [[ "$OS" == "Mac OS X" ]]; then
@@ -726,9 +740,9 @@ else
     echo "libshark is already installed!"
 fi
 
-#############################
-## End of lib installation ##
-#############################
+################################
+## Start of SUMO installation ##
+################################
 
 # change directory to VENTOS
 cd $DIR
@@ -736,28 +750,106 @@ cd $DIR
 cd ..
 
 echo ""
-echo "Downloading SUMO binaries"
+echo "Check main libraries for SUMO"
+echo "============================="
+# should we add "libxerces-c2-dev" ? installing libgdal-dev removes libxerces-c2-dev!
+libs=("automake" "autoconf" "libfox-1.6-dev" "libproj-dev" "libgdal-dev")
+install_LIB_linux libs[@]
+
+echo ""
+echo "Preparing to install SUMO"
 echo "========================="
 
-if [ ! -f VENTOS/sumoBinary/sumo-guiD ]; then
-    echo "downloading sumo-guiD"
-    lftp -e 'pget -n 5 sumo-guiD -o VENTOS/sumoBinary; bye' -p 28 -u userftp,userftp ftp://rubinet.ece.ucdavis.edu/download
+ver=$(sumo 2> /dev/null | grep 'SUMO Version' | awk '{print $3}')
+if [[ "" != "$ver" ]]; then
+    loc=$(which sumo)
+    echo "found SUMO $ver in"
+    echo "    $loc"
+    echo "skip downloading/making SUMO"    
 else
-    echo "sumo-guiD already exists!"
+
+echo ""
+echo "Cloning SUMO git repository"
+echo "==========================="
+# check if SUMO directory exists
+if [ ! -d "VENTOS_SUMO" ]; then
+    # cloning git
+    if ! git clone https://github.com/ManiAm/VENTOS_SUMO; then
+        exit 1
+    fi
+    # make sure the folder is created
+    if [[ ! -d "VENTOS_SUMO" ]]; then
+        echo "VENTOS_SUMO folder does not exist!"
+        exit 1
+    fi
+else
+    echo "VENTOS_SUMO folder already exists!"
 fi
 
-if [ ! -f VENTOS/sumoBinary/sumoD ]; then
-    echo "downloading sumoD"
-    lftp -e 'pget -n 5 sumoD -o VENTOS/sumoBinary; bye' -p 28 -u userftp,userftp ftp://rubinet.ece.ucdavis.edu/download
-else
-    echo "sumoD already exists!"
+echo ""
+echo "Running SUMO configure"
+echo "======================"
+
+cd VENTOS_SUMO
+
+echo "generating configure file ..."
+make -f Makefile.cvs > /dev/null
+
+echo "running configure ..."
+confOut=$( { ./configure --enable-debug --with-proj-gdal --with-proj-libraries=/usr > /tmp/VENTOS_tmp/out.xzevap; } 2>&1 )
+printf "%s \n" "$confOut"
+
+# should we terminate this script
+check=$(echo "$confOut" | grep -e "error" -e "configure: WARNING")
+if [ "" != "$check" ]; then
+    echo ""    # insert new line for readability
+    exit 1
 fi
 
-# make both files executable
-echo -n "making both files executable ..."
-chmod +x VENTOS/sumoBinary/sumo-guiD
-chmod +x VENTOS/sumoBinary/sumoD
-echo "done!"
+# check if SUMO bin is in the path
+SUMO_BIN_DIR=$(pwd)"/bin"
+if [[ ! -d $SUMO_BIN_DIR ]]; then
+   echo "The $SUMO_BIN_DIR directory does not exist!"
+   exit 1
+else
+  # ...then we create a small tmp file to check if the dir is in the path
+  probefile=__second__probe__
+
+  echo '' >$SUMO_BIN_DIR/$probefile
+  chmod +x  $SUMO_BIN_DIR/$probefile
+
+  if ($probefile) >/dev/null 2>/dev/null; then
+    echo "Your PATH contains $SUMO_BIN_DIR. Good!"
+  else
+      printf "WARNING: your PATH doesn't contain $SUMO_BIN_DIR! \nAdd the following line to your .profile or .bash_profile (provided you use bash): \nexport PATH=\$PATH:$SUMO_BIN_DIR \n"
+      printf "\n\e[1;31mAfter changing PATH, close this terminal and run the script again!\e[0m \n"
+      # removing the prob file
+      rm $SUMO_BIN_DIR/$probefile
+      exit 1
+  fi
+
+  # removing the prob file
+  rm $SUMO_BIN_DIR/$probefile
+fi
+
+echo ""
+echo "Making SUMO"
+echo "==========="
+
+# start making SUMO
+printf "\e[1;32mcompiling takes some time, so relax, grab a cup of coffee and \nwatch: https://www.youtube.com/watch?v=A6XUVjK9W4o \e[0m \n"
+echo " "
+make > /dev/null
+echo "make is finished!"
+
+# go out of SUMO folder
+cd ..
+
+fi # end of SUMO installation
+
+######################
+## Finishing up ... ##
+######################
 
 echo ""
 echo "Wrapping-up"
